version: '3'

services:

  app:
    build:
      context: .
    ports:
      - '5858:5858'
      - '9999:9999'
    volumes:
      - .:/opt/app
    links:
      - redis
    depends_on:
      - redis
    command: npm run serve

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
